//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liduo_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sdpost_Member
    {
        public string ID { get; set; }
        public string MemberNo { get; set; }
        public string MemberName { get; set; }
        public string PhoneNo { get; set; }
        public string MemberType { get; set; }
        public string IDNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> Status { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Modifier { get; set; }
        public Nullable<decimal> Scores { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string ShortCode { get; set; }
        public string openid { get; set; }
        public string headimgurl { get; set; }
        public string StoreNo { get; set; }
        public string VIPLevel { get; set; }
    }
}
